config/routes.rb
Rails.application.routes.draw do
  resources :eventsusers
  resources :events
  resources :users, only: %i[new create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  root 'users#index'
end


# def new
# end

# def create
#   @event = Event.find(params[:event_id])
#   @invited_user = User.find(params[:user_id])

#   if @event.attendees.include?(@invited_user)
#     @invited_user.attended_events.delete(@event)
#     flash.notice = "Uninvited " + @invited_user.username + " from " + @event.description
#   else
#     @invited_user.attended_events.push(@event)
#     flash.notice = "Invited " + @invited_user.username + " to " + @event.description
#   end

#   #redirect_to event_path(@event.id)
#   redirect_to :new

# end

# def destroy
# end

app/models/eventsuser.rb
class Eventsuser < ApplicationRecord
end

app/controllers/eventsusers_controller.rb
class EventsusersController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @invited_user = User.find(params[:user_id])

    if @event.attendees.include?(@invited_user)
      @invited_user.attended_events.delete(@event)
      flash.notice = 'Uninvited ' + @invited_user.username + ' from ' + @event.description
    else
      @invited_user.attended_events.push(@event)
      flash.notice = 'Invited ' + @invited_user.username + ' to ' + @event.description
    end

    redirect_to event_path(@event.id)
  end
end

app/helpers/eventsusers_helper.rb
module EventsusersHelper
end

app/views/eventsusers/_form.html.erb
<%= simple_form_for(@eventsuser) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/eventsusers/edit.html.erb
<h1>Editing Eventsuser</h1>

<%= render 'form', eventsuser: @eventsuser %>

<%= link_to 'Show', @eventsuser %> |
<%= link_to 'Back', eventsusers_path %>

app/views/eventsusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventsusers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventsusers.each do |eventsuser| %>
      <tr>
        <td><%= link_to 'Show', eventsuser %></td>
        <td><%= link_to 'Edit', edit_eventsuser_path(eventsuser) %></td>
        <td><%= link_to 'Destroy', eventsuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Eventsuser', new_eventsuser_path %>

app/views/eventsusers/new.html.erb
<h1>New Eventsuser</h1>

<%= render 'form', eventsuser: @eventsuser %>

<%= link_to 'Back', eventsusers_path %>

app/views/eventsusers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_eventsuser_path(@eventsuser) %> |
<%= link_to 'Back', eventsusers_path %>