config/routes.rb
Rails.application.routes.draw do
  resources :eventsusers
  resources :events
  resources :users, only: %i[new create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  root 'users#index'
end


# def new
# end

# def create
#   @event = Event.find(params[:event_id])
#   @invited_user = User.find(params[:user_id])

#   if @event.attendees.include?(@invited_user)
#     @invited_user.attended_events.delete(@event)
#     flash.notice = "Uninvited " + @invited_user.username + " from " + @event.description
#   else
#     @invited_user.attended_events.push(@event)
#     flash.notice = "Invited " + @invited_user.username + " to " + @event.description
#   end

#   #redirect_to event_path(@event.id)
#   redirect_to :new

# end

# def destroy
# end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
  Logged in as <%= current_user.username %>
  <%= link_to 'Log Out', session_path(:id), :method => :delete %>
  <%= link_to 'Event', events_path %>
<% else %>
  <%= link_to 'Sign Up', new_user_path %> or 
  <%= link_to 'Log In', new_session_path %>
<% end %>
<p id=”notice”><%= notice %></p>
<h1>Example</h1>
<p>Lorem ipsum …</p>
    <%= yield %>
  </body>
</html>